version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: software-sales-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: softwaresales
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: